name: Run Dependabot

on:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes
  workflow_dispatch:
  
jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Specify the Node.js version you want to use

      - name: Install dependabot
        run: npm install -g @dependabot/dependatbot-core

      - name: Run Dependabot
        run: dependabot-core update --config-file ../dependabot.yml