name: Run Dependabot

on:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes
  
jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v1
        with:
          directory: ../